# Site settings
title:          Tale
description:    "FE DEV.log"
url:            "https://ch3coo2ca.github.io"
remote_theme:   chesterhow/tale
# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         jylee
  url:          https://chester.how

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale